---
# Configuración de base de datos
- name: Instalar MariaDB
  ansible.builtin.apt:
    name: mariadb-server
    state: present
    update_cache: true

- name: Asegurar que MariaDB está en ejecución
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
