---
# Configuración de servidor web
- name: Instalar Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Asegurar que Nginx está en ejecución
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
